version: "3.8"

services:

  app:
    build: .
    container_name: employee_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app     # maps your local folder to container so code changes reflect

  db:
    image: postgres:15
    container_name: employee_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: employee_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data   # persists DB data even after container stops
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # run SQL on first startup
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: employee_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: